services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USE_CUDA: "true"
        USE_OLLAMA: "true"
        USE_CUDA_VER: "cu128"
    image: 'open-webui:jetson'
    volumes:
      - 'open-webui:/app/backend/data'
    environment:
      SERVICE_FQDN_OPENWEBUI_8080: "${SERVICE_FQDN_OPENWEBUI_8080:-}"
      OLLAMA_BASE_URL: "http://192.168.1.81:11434"
      OLLAMA_STREAM: "false"            
      WEBUI_SECRET_KEY: "${WEBUI_SECRET_KEY:-changeme}"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      
volumes:
  open-webui:
    driver: local
