##services:
#  ollama-api:
#    image: 'ollama/ollama:latest'
#    volumes:
#      - 'ollama:/root/.ollama'
#    healthcheck:
#      test:
#        - CMD
#        - ollama
#        - list
#      interval: 5s
#      timeout: 30s
#      retries: 10
##  open-webui:
##    image: 'ghcr.io/open-webui/open-webui:main'
##    volumes:
##      - 'open-webui:/app/backend/data'
#    depends_on:
#      - ollama-api
##    environment:
##     - SERVICE_FQDN_OLLAMA_8080
##      - 'OLLAMA_BASE_URL=http://192.168.1.81:11434'
##    healthcheck:
##      test:
##        - CMD
##        - curl
##        - '-f'
##        - 'http://127.0.0.1:8080'
##      interval: 5s
##      timeout: 30s
##      retries: 10


services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USE_CUDA: "true"
        USE_OLLAMA: "false"
        USE_CUDA_VER: "cu128"
    image: 'open-webui:jetson'
    volumes:
      - 'open-webui:/app/backend/data'
    environment:
      SERVICE_FQDN_OPENWEBUI_8080: "${SERVICE_FQDN_OPENWEBUI_8080:-}"
      OLLAMA_BASE_URL: "http://192.168.1.81:11434"
      WEBUI_SECRET_KEY: "${WEBUI_SECRET_KEY:-changeme}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      
volumes:
  open-webui:
    driver: local


#services:
#  ollama:
#    volumes:
#      - ollama:/root/.ollama
#    container_name: ollama
#    pull_policy: always
#    tty: true
#    restart: unless-stopped
#    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

#  open-webui:
#    build:
#      context: .
#      args:
#        OLLAMA_BASE_URL: 'http://127.0.0.1:11434'
#      dockerfile: Dockerfile
#    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
#    container_name: open-webui
#    volumes:
#      - open-webui:/app/backend/data
#    depends_on:
#      - ollama
#    ports:
#      - ${OPEN_WEBUI_PORT-3000}:8080
#    environment:
#      - 'OLLAMA_BASE_URL=http://127.0.0.1:11434'
#      - 'WEBUI_SECRET_KEY='
#    extra_hosts:
#      - host.docker.internal:host-gateway
#    restart: unless-stopped

#volumes:
#  ollama: {}
#  open-webui: {}

#services:
#  open-webui:
#    image: ghcr.io/open-webui/open-webui:main
#    container_name: open-webui
#    ports:
#      - "3000:8080"
#    volumes:
#      - open-webui:/app/backend/data
#    environment:
#      - WEBUI_SECRET_KEY=supersecret
#      - 'OLLAMA_BASE_URL=http://192.168.1.81:11434'
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#    restart: unless-stopped

#volumes:
#  open-webui: {}
  
#volumes:
#  open-webui: {}

#  open-webui:
#    image: 'ghcr.io/open-webui/open-webui:main'
#    volumes:
#      - 'open-webui:/app/backend/data'
#    depends_on:
#      - ollama-api
#    environment:
#      - SERVICE_FQDN_OLLAMA_8087
#      - 'OLLAMA_BASE_URL=http://127.0.0.1:11434'
#    healthcheck:
#      test:
#        - CMD
#        - curl
#        - '-f'
#        - 'http://127.0.0.1:8087'
#      interval: #5s
#      timeout: 30s
#      retries: 10
